dist: trusty
sudo: true
language: cpp
  
before_install:
  - mkdir $HOME/usr
  - export PATH="$HOME/usr/bin:$PATH"
  - wget https://cmake.org/files/v3.12/cmake-3.12.0-Linux-x86_64.sh
  - chmod +x cmake-3.12.0-Linux-x86_64.sh
  - ./cmake-3.7.2-Linux-x86_64.sh --prefix=$HOME/usr --exclude-subdir --skip-license

script:
  - cmake .
  - cmake --build .